name: Release Notes

on:
  push:
    tags:
      - '*'

jobs:
  notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Generate Release Name
        run: |
          NAME=$(npx node-neb-muz random-song)
          echo ${NAME}
          echo "RELEASE_NAME=${NAME}" >> $GITHUB_ENV
      - uses: actions/setup-node@v5
      - uses: ncipollo/release-action@v1
        with:
          name: ${{env.RELEASE_NAME}}
          token: ${{ secrets.BORGZORT_TOKEN }}
          generateReleaseNotes: true
      - uses: act10ns/slack@v2
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          message: Release Failed {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }}
